### PR TITLE
📝 : add missing documentation about authorization

### PR DESCRIPTION
**Pull request by binlab**
Hello!
I have added missed documentation about which credentials should use for entering when I can't have found it. Spied in the source code of an application.

### CODE REVIEW

**Comment by juwit** [comment]
Hi @binlab, and thank you again for contributing. 

Can you update your commit message?
We're using `gitmoji` as a commit convention, and it allows us to generate our CHANGELOG.md easily (we'll add that part in our CONTRIBUTING.md)

Maybe with this message: 

```
:pencil: : add missing documentation about authorization
```

Thanks :)

**Comment by binlab** [comment]
yes, sure!

**Comment by binlab** [comment]
I didn't understand how to paste it. Found a solution but still, I'm not sure that is as you are expected :-)

**Comment by juwit** [comment]
Oh, I meant not the title of the PR, but the git message itself, by using `git amend` :)

**Comment by binlab** [comment]
oh, yep!  now it's clear. thanks! :)

**Comment by juwit** [comment]
Perfect, thank you !

**Pull request merged**
